apiVersion: v1
kind: Service
metadata:
  name: igokochi-backend-nodeport
spec:
  type: NodePort
  selector:
    app: igokochi-backend
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400 # choose any free port 30000–32767
