apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  selector:
    app: mysql-igokochi
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
